### ISSUE TITLE
Support for multiple source datasets?

### ISSUE THREAD

**Issue by servebeer** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#1]
I don't see any mentions that the script can support multiple source datasets. If they are supported, do you separate them with spaces, commas, etc.?

**Comment by SpaceinvaderOne** [comment]
The script has been rewritten but I decided not to allow multiple datasets to be snapshoted and replicated. The script would just become too complex with multiple source and destinations especially with things like the rsync incremental hardlink replication.
I find it best just to use the script multiple times for different datasets

**Comment by servebeer** [comment]
Thanks for the reply!

**Comment by servebeer** [comment]
I just updated the script on my UR box, it works great, thanks!
