### ISSUE TITLE
Request: Exclude specific subdatasets from replication

### ISSUE THREAD

**Issue by hobbis75** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#10]
Hi
Is there a way to configure the script to exclude certain sub datasets from replication?

I have a dataset called "media". Within that I have several sub datasets for magazines, books, music, movies and tvshows
I want to include magazines, books and music, but not movies and tvshows

The workaround I can see is to move the movies and tvshows to a separate dataset, but if possible, I would like to keep my current layout.

Thanks for a great script and explaining videos btw.

Regards HoBBiS

**Comment by keywal** [comment]
While not an ideal strategy, i got around this by classing a dataset like this:
(using your info as an example)

`source_dataset="media/magazines"`

You then would need another copy of the script with the source being:

`source_dataset="media/books"`

of course create more as needed.
Until something better comes along, this is the way! :)

**Comment by hobbis75** [comment]
That's a smart workaround. Thank you!

**Comment by Jarikk** [comment]
Wouldn't it be simpler to have 'media/movies' as a regular folder instead of a dataset?

**Comment by hobbis75** [comment]
> Wouldn't it be simpler to have 'media/movies' as a regular folder instead of a dataset?

I was not aware that that was a option using this script. Thanks. I have done a workaround setting up a separate share for my movies and tvshows library so now it works for me as intended. Plex did not like that, but in the end, it worked fine :)
