### ISSUE TITLE
Replication fails

### ISSUE THREAD

**Issue by mothy-tim** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#16]
Hi, after loads of issues changing to zfs I finally got to be able to run the create datasets script and that ran without errors! So I set up this script and every time it fails to replicate the Plex dataset! It also would fail if I copied using unRAID file manager and appdata, backup plugin, so I restored from an older backup and that fixed copying and backing up in the plugin, but still fails with zfs replication! Not sure what to try next? Thanks and thanks for your amazing videos, they've helped me loads over the years!!
[log (1).zip](https://github.com/SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications/files/12641467/log.1.zip)

**Comment by SpaceinvaderOne** [comment]
Hi. Sorry to hear you have this problem. Looking in your log
```
Resuming interrupted zfs send/receive from cache/appdata/PlexMediaServer to disk3/Backups/cache_appdata/PlexMediaServer (~ 13.5 GB remaining):
warning: cannot send 'cache/appdata/PlexMediaServer@autosnap_2023-09-09_17:53:23_monthly': Input/output error
cannot receive resume stream: checksum mismatch or incomplete stream.
Partially received snapshot is saved.
```

The Input/output error is basically it is unable to read the data from the source. This could indicate a hardware failure on the source dataset or a corruption issue. The warning specifically mentions an issue with the snapshot 'cache/appdata/PlexMediaServer@autosnap_2023-09-09_17:53:23_monthly', suggesting that there might be an issue with this specific snapshot.

Then the error, "cannot receive resume stream: checksum mismatch or incomplete stream," indicates that the data being received on the target is not matching the expected checksum, or that the stream is incomplete. This means that the data received so far might be corrupted, or the stream was interrupted before it could finish, resulting in an incomplete transfer.

Try running a zpool status and zfs scrub on the source pool and see if that shows any issues

**Comment by mothy-tim** [comment]
Thank you, I tried that but it didn't work. I had to delete the offending snapshot and it now works! I think the data got corrupted somehow when running the change to dataset script and so deleting the snapshot taken before restoring an old backup seems to have cured the issue! Cheers, Tim
