### ISSUE TITLE
Destination zpools

### ISSUE THREAD

**Issue by hypascend** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#19]
I am trying to figure our how to target the zfs-backup "share" rather than a specific zpool as I have 10 disks now with ZFS.  Is this possible?

**Comment by SpaceinvaderOne** [comment]
Hi if you want to use ZFS replication it has to be done to a destination that is a zpool. If you have multi disks in the unraid array in the destination that are zfs formatted disks then each one will be a pool. ie   disk1/datasetname    disk10/dataset name
If you want to use a share target then tou would need to use rsync replication by setting the the replication type to rsync in the script
