### ISSUE TITLE
Separate snapshot and replication schedule

### ISSUE THREAD

**Issue by Serephucus** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#20]
Quick feature request. I'd like the ability to define snapshot retention and replication frequency separately.

In my case, I'm taking hourly snapshots, but I don't necessarily want the array being written to every hour with replication.
So, it would be nice to be able to say, keep x hourly snaps, y daily, r monthly, t yearly, and replicate hourly/daily/weekly, etc.

Fantastic script, and thank you so much for all of your unRAID contributions over the years. It wouldn't be what it is today without you.

**Comment by SpaceinvaderOne** [comment]
Hi @Serephucus  Thanks for your kind comments.
Re the Separate snapshot and replication schedule, this is possible to do already.
The script runs from the Unraid userscripts which sets the cron schedule for when it runs.
So basically you would use the script in 2 separate instances. 

The first one (which does your 1 hourly snapshots) in the variables just make sure `autosnapshots="yes"`  to ensure snapshots are run. But set `replication="none" ` the script with these settings will only do the snapshoting.  Have this script running hourly in the userscripts schedule.

The second script (this would just do replication) in the variables just make sure `autosnapshots="no"`  this will disable the snapshots for this script. But have `replication="zfs"` (if using zfs replication) or  `replication="rsync" (if using rsync replication)   This script now will only do the replication. You can set this to run daily.

Hope this helps

**Comment by Serephucus** [comment]
Thanks for the reply!

I'd actually thought of that, I'd just like to avoid too much duplication, as in my experience that can lead to user error. 
At the moment I already have three copies of it for different datasets/snapshot retention policies.
Just thought I'd flag it here in case you thought it was worth including, etc. If not, no stress!

**Comment by SpaceinvaderOne** [comment]
I have thought of implementing multi pools and datasets in the one script. But it is a fine balance between the script getting too complex for newbies to use if there is too much to fill in as variables etc. maybe i could add a basic and advanced script.
 But in the future I do hope to move the zfs scripts into a plugin at some point, then the setup for the average user would be easier.
