### ISSUE TITLE
'Strict-mirror' not deleting destination snapshots

### ISSUE THREAD

**Issue by devlinandrew** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#24]
I have ZFS replication set up and it looks to be working for everything except the destination snapshot deletion. I have 16 snapshots per share in my cache pool, but 87 on the replication pool.  It looks like the script isn't deleting the destination snapshots that have been deleted from the source. Any ideas on where to troubleshoot?

**Comment by arturoovf** [comment]
just checking, do you have syncoid_mode="strict-mirror"?

**Comment by devlinandrew** [comment]
> Try this solution: #22

This fixed the issue for me as well...thanks!
