### ISSUE TITLE
Retention parameters being ignored?

### ISSUE THREAD

**Issue by elliottmarter** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#25]
Might be doing something wrong here but I cant seem to make sense of why its not working.

Parameters set as follows as an example I would like to keep 2 weeks of snapshots, 1 per day...

![image](https://github.com/SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications/assets/32469521/f224ac7e-588a-4283-b60e-b555fd7e3523)

However checking all the container snapshots its still taking monthly and weekly ones and has not purged ones from over 14 days ago?

![image](https://github.com/SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications/assets/32469521/e325a268-baf4-4ad6-a88d-5b09a90c6cc5)

Any advice appreciated if I am making a mistake :)

**Comment by eagleeyedpixel** [comment]
Confirming I am also seeing this - Version: 6.12.6.
Regardless of the retention settings - no snapshots are being purged.

Snapshots are being created fine.

**Comment by BenSanborn** [comment]
I am also having this issue, nothing is being pruned and drive just keeps growing.

unraid 6.12.6 here.

**Comment by SpaceinvaderOne** [comment]
When you first run the script, it'll create a config file in the share system/sanoid/poolnameofdataset. If the script notices the file's already there, it won't make a new one. This means if you tweak the retention settings in the script, it won't update that config file. So, if you change those settings, you got to delete that folder to get the script to make a new config file with your updated settings.

**Comment by viptampa** [comment]
@SpaceinvaderOne - I see that my snapshots on my 'main' datasets are being pruned, but not the ones that are replicated to the ZFS drive in the array (same server).  How can I prune zfs snapshots on those datasets?

**Comment by elliottmarter** [comment]
closing as SpaceinvaderOne's reply above fixed the issue (sorry did not realize this was still open!)

**Comment by Blasman** [comment]
> When you first run the script, it'll create a config file in the share system/sanoid/poolnameofdataset. If the script notices the file's already there, it won't make a new one. This means if you tweak the retention settings in the script, it won't update that config file. So, if you change those settings, you got to delete that folder to get the script to make a new config file with your updated settings.

Instead of simply doing `return` if the config file exists, you could instead have the script update any changes made to the sanoid retention policy in the script config:
```  # check if a configuration file has already been created from a previous run, if so exit the function
  if [ -f "${sanoid_config_complete_path}sanoid.conf" ]; then
      update_setting() {
          local key=$1 new_value=$2 current_value
          current_value=$(grep "^$key = " "${sanoid_config_complete_path}sanoid.conf" | awk -F ' = ' '{print $2}')
          if [[ "$current_value" != "$new_value" ]]; then
              sed -i "s/^$key = .*/$key = $new_value/" "${sanoid_config_complete_path}sanoid.conf"
              echo "[CONFIG CHANGE] Updated '$key' to '$new_value' in '${sanoid_config_complete_path}sanoid.conf'."
          fi
      }
      update_setting "hourly" "$snapshot_hours"
      update_setting "daily" "$snapshot_days"
      update_setting "weekly" "$snapshot_weeks"
      update_setting "monthly" "$snapshot_months"
      update_setting "yearly" "$snapshot_years"
  fi

**Comment by 808mp5** [comment]
`here's` one solution that could be implemented.. i noticed this too.. and what made the (non-breaking bug) more irritating is i used the same script for different datasets ... with the intention of having different schedules

replace block starting at line 232 with this.. what this does is recreate the sanoid.conf if the retention doesn't match (updated retention policy, or running same script with a different retention policy)

```
# This function will build (or refresh) a Sanoid config file for use with the script
create_sanoid_config() {
  # only make config if autosnapshots is set to "yes"
  if [[ "$autosnapshots" != "yes" ]]; then
    return
  fi

  # Paths
  local dir="$sanoid_config_complete_path"
  local target_conf="${sanoid_config_complete_path}sanoid.conf"

  # Ensure directory exists
  mkdir -p "$dir"

  # Ensure defaults are present (one-time)
  if [[ ! -f "${sanoid_config_complete_path}sanoid.defaults.conf" ]]; then
    cp /etc/sanoid/sanoid.defaults.conf "${sanoid_config_complete_path}sanoid.defaults.conf"
  fi

  # Always (re)write sanoid.conf so retention changes take effect
  cat > "$target_conf" <<EOF
[${source_path}]
use_template = production
recursive = yes

[template_production]
hourly = ${snapshot_hours}
daily  = ${snapshot_days}
weekly = ${snapshot_weeks}
monthly = ${snapshot_months}
yearly  = ${snapshot_years}
autosnap = yes
autoprune = yes
EOF
  echo "Wrote $target_conf"
}
`
# This function will build (or refresh) a Sanoid config file for use with the script
create_sanoid_config() {
  # only make config if autosnapshots is set to "yes"
  if [[ "$autosnapshots" != "yes" ]]; then
    return
  fi

  # Paths
  local dir="$sanoid_config_complete_path"
  local target_conf="${sanoid_config_complete_path}sanoid.conf"

  # Ensure directory exists
  mkdir -p "$dir"

  # Ensure defaults are present (one-time)
  if [[ ! -f "${sanoid_config_complete_path}sanoid.defaults.conf" ]]; then
    cp /etc/sanoid/sanoid.defaults.conf "${sanoid_config_complete_path}sanoid.defaults.conf"
  fi

  # Always (re)write sanoid.conf so retention changes take effect
  cat > "$target_conf" <<EOF
[${source_path}]
use_template = production
recursive = yes

[template_production]
hourly = ${snapshot_hours}
daily  = ${snapshot_days}
weekly = ${snapshot_weeks}
monthly = ${snapshot_months}
yearly  = ${snapshot_years}
autosnap = yes
autoprune = yes
EOF
  echo "Wrote $target_conf"
}
```
