### ISSUE TITLE
Document steps to recover

### ISSUE THREAD

**Issue by d3mystified** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#4]
This is a great script - thanks @SpaceinvaderOne.

One ask though - it would be great to also document how to recover from snapshots (rsync and zfs replication, incremental and full). So maybe a couple of scenarios to add to readme:

1. Recover an individual file from a snapshot (say I messed up my radarr db which is in its own dataset)
2. Recover an entire dataset (say my entire plex install)
3. Recover the entire pool (say my single appdata zfs drive died and I need to recover snapshot to a new one)

Thanks!

**Comment by SpaceinvaderOne** [comment]
i will make a video to explain this very soon.

**Comment by wadernat0rz** [comment]
It would also be great to understand how to recover using the snapshot backups.

**Comment by wadernat0rz** [comment]
> This has been closed because it's apparently been done, but I can't for the life of me find any documentation on recovery steps. I'm trying to restore an earlier snapshot of one of my container appdata folders, and everything I try results in an empty folder.

Also waiting for the answer to this

**Comment by NeoDuder** [comment]
Yeah. I need it ASAP, as one of Containers has went back to default settings and any attempt to rollback a snapshot results in an empty folder. I don't have a clue how to restore the replicated versions.

**Comment by NeoDuder** [comment]
> @NeoDuder - were you ever able to figure out a solution?

Nope. I have a single disk for my ZFS backups and don't have the first clue on how to restore from it :P
