### ISSUE TITLE
Unraid 7 beta 1 - issue (libcrypto.so.1.1)

### ISSUE THREAD

**Issue by angelgtc87** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#41]
Ever since I updated to new unraid I'm getting an error, the issue seems to be related to libcrypto.so.1.1 lookup, I see new unraid has libcrypto.so.3, so just wanted to report that issue.

Thanks !

```
Starting ZFS replication using syncoid with mode: strict-mirror
Sending incremental nvme_cache/temp@syncoid_Loki_2024-06-27:02:30:07-GMT-04:00 ... syncoid_Loki_2024-06-29:02:30:06-GMT-04:00 (~ 15.9 GB):
mbuffer: error while loading shared libraries: libcrypto.so.1.1: cannot open shared object file: No such file or directory
cannot receive: failed to read from stream
warning: cannot send 'nvme_cache/temp@syncoid_Loki_2024-06-29:02:30:06-GMT-04:00': Broken pipe
CRITICAL ERROR: zfs send -I 'nvme_cache/temp'@'syncoid_Loki_2024-06-27:02:30:07-GMT-04:00' 'nvme_cache/temp'@'syncoid_Loki_2024-06-29:02:30:06-GMT-04:00' | mbuffer -q -s 128k -m 16M | pv -p -t -e -r -b -s 17097423024 | zfs receive -s -F 'ssd_cache/zfs_backups/nvme_cache_temp' 2>&1 failed: 256 at /usr/local/sbin/syncoid line 889.
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 218 100 15 100 203 4 62 0:00:03 0:00:03 --:--:-- 67
pruning the automatic snapshots using sanoid based off retention policy
Script Finished Jun 29, 2024 02:30.10
```

this was working fine in unraid 6.X.X

**Comment by E5rael** [comment]
I tried to make a symbolic link

`sudo ln -s /usr/lib64/libcrypto.so /usr/lib64/libcrypto.so.1.1`

as suggested by avently [here](https://github.com/simplex-chat/simplex-chat/issues/1274). Then I tried to run the script and now the error message looks like so:

> mbuffer: /usr/lib64/libcrypto.so.1.1: version `OPENSSL_1_1_0' not found (required by mbuffer)
> cannot receive: failed to read from stream
> warning: cannot send 'primary/system@autosnap_2024-07-06_14:32:30_monthly': Broken pipe
> CRITICAL ERROR: zfs send 'primary/system'@'autosnap_2024-07-06_14:32:30_monthly' | mbuffer -q -s 128k -m 16M | pv -p -t -e -r -b -s 464230384 | zfs receive -s -F 'primary/test_backup/primary_system' failed: 256 at /usr/local/sbin/syncoid line 549.

Seems like the script requires OpenSSL 1.1.0, while the new Unraid version has version 3.3.0.

**Comment by SpaceinvaderOne** [comment]
Hi as you are running Unraid 7, it no longer includes OpenSSL 1.1.0 and instead uses OpenSSL 3.
Sanoid/Syncoid uses mbuffer, which is now installed as a default package in Unraid. Since Unraid 7 uses OpenSSL 3, the mbuffer package that the Sanoid plugin installs is not compatible, hence the issue your having.
To fix this run the following command in the Unraid terminal
`sed -i '/^mbuffer-20240107-x86_64-1_SBo.tgz/d' /boot/config/plugins/unRAID6-Sanoid.plg
`
This will stop the Sanoid plugin from installing its own version of mbuffer, so avoid overwriting of the native Unraid version. Just run that command and reboot the Server and you will be good to go :)

**Comment by angelgtc87** [comment]
@SpaceinvaderOne worked !! thank you :)

**Comment by Commifreak** [comment]
> the mbuffer package that the Sanoid plugin installs is not compatible

Did someone already told this the sanoid plugin owner? https://github.com/Steini1984/unRAID6-Sainoid/issues

Maybe the owner can fix this :)
