### ISSUE TITLE
Lauch the script from the destination server ?

### ISSUE THREAD

**Issue by keichitokuna** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#6]
Hello,

I use two Unraid servers, the main and the backup.

Every day, my smartplug automatically turn on the backup server, which launch a rsync script at array startup (this one : https://forums.unraid.net/topic/97958-rsync-incremental-backup/) through rsync-server (read-only access to the main for security reason) in order to backup my main array.

I was waiting for your next video, in order to do the appdata/VM part using ZFS.

As the backup will run the rsync backup of the array, i would like to launch your script AFTER and then powerdown.

Did you think that launching the script via ssh from the backup server to the main is a good approach ?
Will the backup server knows knows when the script finished ?

Thanks !!

K.

**Comment by SpaceinvaderOne** [comment]
Um Yes it would work that way and would be fairly easy to set up.But no the backup server wouldnt "know" it had finished without more.
You would need to do the following
Add a line to the end replication script on the main server to make a flag when its finished. (would put a flag file in the unraid /tmp directory (ram)
`touch /tmp/zfs_rep_complete_flag.txt`

Then make a userscript on backup server based around this

```
#!/bin/bash
# start script on host unraid
ssh root@unraid "/path/to/backup_script_on_host.sh"
# check for flag 2 see if finished yet
while true; do
    if ssh root@unraid "test -f /tmp/zfs_rep_complete_flag.txt"; then
        # Remove the completion flag from the host
        ssh root@unraid "rm /tmp/zfs_rep_complete_flag.txt"
        echo "Backup complete. Removing completion flag."
        break
    else
        echo "Waiting for backup to complete..."
        sleep 60  # wait for 60 seconds before checking again
    fi
done
# then when done shutdown the backup server
echo "Finished, shutting down the backup server..."
shutdown -h now
```


It would be better I think to  run the actual replication script on the backup server as it woulld be cleaner (although no reason not to do the above) I would need to add an option the script for the source to be remote as opposed to the destination. Then the script would ssh to host for the source pool and then replicate to local destination. I will think about updating the script if i get time :)

**Comment by keichitokuna** [comment]
Thanks for the fast reply !

After a afternoon of woork, i ended with that in backup server's UserScripts (simplified version) :

```
#!/bin/bash

# Backup Yggdrasil cache zfs (your script)
    ssh root@yggdrasil.local "bash '/boot/config/plugins/user.scripts/scripts/Backup - ZFS appdata/script'"
    ssh root@yggdrasil.local "bash '/boot/config/plugins/user.scripts/scripts/Backup - ZFS system/script'"
    ssh root@yggdrasil.local "bash '/boot/config/plugins/user.scripts/scripts/Backup - ZFS domains/script'"

# Backup Yggdrasil array xfs (rsync-incremental-backup script)
    bash "/boot/config/plugins/user.scripts/scripts//boot/config/plugins/user.scripts/scripts/1 - Backup Yggdrasil/script"

# Backup Yggdrasil Tree (a homemade script with incremential tree backup like : ssh root@yggdrasil.local "tree -N '$tree_folder/$folder'" > "$backup_directory/$folder.txt" 2>&1)
    bash "/boot/config/plugins/user.scripts/scripts/3 - Tree Yggdrasil/script"

# Turn off
powerdown
```

Using ssh, it seems that i can follow the script.

It is not ideal because i need to deploy 3 scripts on the main server (i would prefer having all scripts on the backup server), but good enough.

I will maybe try to use a loop inside your script, then i can loop on my three dataset with the same script.

Backup/Restore Appdata and VM Backup are now retired thanks to you. ZFS is so more fast !

Thanks again

K.
