### ISSUE TITLE
ssmtp: Authorization failed

### ISSUE THREAD

**Issue by Toskache** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#7]
First of all: Great work an thank you for your effort!

When I execute the script (manually via "User Skripts" everything seems working perfekt.
But there is a dubious line in the output:

> ssmtp: Authorization failed (535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6)

Full output:

> Script location: /tmp/user.scripts/tmpScripts/auto snapshots system/script
> Note that closing this window will abort the execution of this script
> Replication target is a local/same server.
> All pre-run checks passed. Continuing...
> creating the automatic snapshots using sanoid based off retention policy
> ssmtp: Authorization failed (535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6)
> Starting ZFS replication using syncoid with mode: strict-mirror
> WARN: mbuffer not available on source [local machine] - sync will continue without source buffering.
> WARN: mbuffer not available on target [local machine] - sync will continue without target buffering.
> Sending incremental cache/system@syncoid_nas_2023-08-26:17:48:12-GMT02:00 ... syncoid_nas_2023-08-26:17:50:59-GMT02:00 (~ 4 KB):
> Sending incremental cache/system/docker@syncoid_nas_2023-08-26:17:48:12-GMT02:00 ... syncoid_nas_2023-08-26:17:50:59-GMT02:00 (~ 16.6 MB):
> Sending incremental cache/system/sanoid@syncoid_nas_2023-08-26:17:48:34-GMT02:00 ... syncoid_nas_2023-08-26:17:51:00-GMT02:00 (~ 4 KB):
> ssmtp: Authorization failed (535 5.7.8 Error: authentication failed: UGFzc3dvcmQ6)
> pruning the automatic snapshots using sanoid based off retention policy

I can't find anything in the script like that. Do you. know where it comes from? 

BR
 George

**Comment by SpaceinvaderOne** [comment]
Hi George,
The error you're seeing is due to the email notifications in the Unraid GUI not being configured correctly. The script leverages Unraid's notification system to send messages, so any issues there will reflect in our script's output. 

the line that uses the unraid noticications is
```
 # Call the Unraid notification script
    /usr/local/emhttp/webGui/scripts/notify -s "Backup Notification" -d "$message" -i "$severity"
```
Please check and ensure the email settings in Unraid's notifications are set up correctly.

**Comment by Toskache** [comment]
Thank you! There was indeed a error in the email-notification setting!
