### ISSUE TITLE
Issue: Question - Output echo to Syslog

### ISSUE THREAD

**Issue by masterwishx** [SpaceinvaderOne/Unraid_ZFS_Dataset_Snapshot_and_Replications#8]
Thanks , i used you script that month ago ,now moved to new one .
is it good idea to use "`exec 1> >(logger -s -t $PROG_NAME) 2>&1`" in bash script for output (echo) to syslog ?

#Redirecting bash script output (echo) to syslog
```
PROG_NAME="ZFS_SnapShot"
exec 1> >(logger -s -t $PROG_NAME) 2>&1
```
####################

**Comment by SpaceinvaderOne** [comment]
You can do but personally i wouldnt. Basically the script's output is quiteverbose, it might clutter the syslog and make it more difficult to sift through and find other important system messages.
